# -*- coding: utf-8 -*-
"""Copy of InFormAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFOgra3Rl_dm_9HNJMS48-xOLBgK_Knp
"""

!pip install pandas openpyxl

# ===========================
# 📚 Imports
# ===========================
import pandas as pd
import io
from IPython.display import display
import ipywidgets as widgets

# ===========================
# 📤 Step 1: Upload File
# ===========================
print("📁 Please upload a CSV or Excel file:")

from google.colab import files
uploaded = files.upload()

if not uploaded:
    raise Exception("No file uploaded!")

file_name = list(uploaded.keys())[0]

if file_name.endswith(".csv"):
    df = pd.read_csv(io.BytesIO(uploaded[file_name]))
else:
    df = pd.read_excel(io.BytesIO(uploaded[file_name]))

print("\n✅ File uploaded successfully!")
print(f"Detected columns: {list(df.columns)}")

# ===========================
# 🧾 Step 2: Owner Details
# ===========================
owner_email = input("\nEnter your (owner) email: ")
colleague_emails = input("Enter colleagues' emails (comma-separated): ").split(",")

# ===========================
# 🧩 Step 3: Generate Simple Form
# ===========================
print("\n--- Fill form sample (simulating one response) ---\n")

responses = {}
for col in df.columns:
    responses[col] = input(f"Enter value for '{col}': ")

# Convert to DataFrame
response_df = pd.DataFrame([responses])

# ===========================
# 💾 Step 4: Save Responses
# ===========================
try:
    existing = pd.read_csv("responses.csv")
    final_df = pd.concat([existing, response_df], ignore_index=True)
except FileNotFoundError:
    final_df = response_df

final_df.to_csv("responses.csv", index=False)
print("\n✅ Response saved successfully!")

# ===========================
# 📊 Step 5: Show Collected Data
# ===========================
print("\n📋 Current collected responses:")
display(final_df)

# ===========================
# 📤 Step 6: Download Option
# ===========================
from google.colab import files
final_df.to_csv("responses.csv", index=False)
files.download("responses.csv")

# ===========================
# ✉️ Step 7: Simulate Sending Links
# ===========================
print("\n📨 Simulating sending form link to colleagues:")
form_link = "https://example.com/form"  # Placeholder for actual link (Streamlit later)
for email in colleague_emails:
    email = email.strip()
    if email:
        print(f"✅ Sent simulated form link to: {email} ({form_link})")

print("\n🎉 All done! You can move this logic to Streamlit for full web automation.")

import streamlit as st
import pandas as pd
import os

st.set_page_config(page_title="Smart Form Automation", layout="wide")

st.title("📄 Smart Form Automation")

# =============================
# Step 1: Upload a File
# =============================
uploaded_file = st.file_uploader("📤 Upload a CSV or Excel file", type=["csv", "xlsx"])

if uploaded_file:
    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)

    st.success("✅ File uploaded successfully!")
    st.write("Detected columns:", list(df.columns))

    # =============================
    # Step 2: Owner Details
    # =============================
    st.header("👤 Owner Details")
    owner_email = st.text_input("Owner Email")
    colleagues = st.text_area("Colleagues' emails (comma-separated)")

    # =============================
    # Step 3: Generate Form Fields
    # =============================
    st.header("📝 Fill Sample Form (Preview)")
    responses = {}
    for col in df.columns:
        responses[col] = st.text_input(f"{col}", key=col)

    # =============================
    # Step 4: Save Responses
    # =============================
    if st.button("💾 Save Response"):
        new_data = pd.DataFrame([responses])

        os.makedirs("data", exist_ok=True)
        file_path = "data/responses.csv"

        if os.path.exists(file_path):
            existing = pd.read_csv(file_path)
            final_df = pd.concat([existing, new_data], ignore_index=True)
        else:
            final_df = new_data

        final_df.to_csv(file_path, index=False)
        st.success("✅ Response saved successfully!")

    # =============================
    # Step 5: View All Responses
    # =============================
    if st.button("📊 View All Responses"):
        file_path = "data/responses.csv"
        if os.path.exists(file_path):
            responses_df = pd.read_csv(file_path)
            st.dataframe(responses_df)
            st.download_button("⬇️ Download CSV", responses_df.to_csv(index=False), "responses.csv")
        else:
            st.warning("No responses found yet!")

    # =============================
    # Step 6: Simulate Sending Links
    # =============================
    if st.button("📨 Simulate Sending Form Link"):
        form_link = "https://yourapp.streamlit.app"  # placeholder
        if colleagues:
            st.info("Sending links to:")
            for email in [x.strip() for x in colleagues.split(",") if x.strip()]:
                st.write(f"✅ {email}: {form_link}")
        else:
            st.warning("Please enter at least one colleague email.")

