# -*- coding: utf-8 -*-
"""form.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJVIgOp9YA89oh1HlZhXVZ7oobmONP3p
"""

import streamlit as st
import pandas as pd
import os

st.title("📝 Fill Out the Form")

# Read template headers
template_path = "data/form_template.csv"
if not os.path.exists(template_path):
    st.error("Form not available. Ask the owner to upload it first.")
else:
    df = pd.read_csv(template_path)
    responses = {}
    for col in df.columns:
        responses[col] = st.text_input(f"{col}")

    if st.button("✅ Submit"):
        os.makedirs("data", exist_ok=True)
        file_path = "data/responses.csv"
        new_data = pd.DataFrame([responses])
        if os.path.exists(file_path):
            existing = pd.read_csv(file_path)
            final_df = pd.concat([existing, new_data], ignore_index=True)
        else:
            final_df = new_data
        final_df.to_csv(file_path, index=False)
        st.success("🎉 Your response has been submitted!")

