# -*- coding: utf-8 -*-
"""owner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJVIgOp9YA89oh1HlZhXVZ7oobmONP3p
"""

import streamlit as st
import pandas as pd
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

st.title("👤 Owner Dashboard")

uploaded_file = st.file_uploader("Upload your CSV or Excel file", type=["csv", "xlsx"])
if uploaded_file:
    df = pd.read_csv(uploaded_file) if uploaded_file.name.endswith(".csv") else pd.read_excel(uploaded_file)
    st.success("✅ File uploaded successfully!")
    st.write("Detected columns:", list(df.columns))

    owner_email = st.text_input("Owner Email")
    colleagues = st.text_area("Colleagues' emails (comma-separated)")

    sender_email = st.text_input("Sender Gmail address")
    sender_password = st.text_input("App Password", type="password")

    # Save file headers to identify this form
    os.makedirs("data", exist_ok=True)
    df.head(0).to_csv("data/form_template.csv", index=False)

    if st.button("✉️ Send Form Link"):
        subject = "Please fill out this form"
        # Replace localhost link with your deployed URL later
        form_link = "http://localhost:8501/Form"
        body = f"""Hi there,

You've been invited to fill out a new form.

👉 Click here to fill the form: {form_link}

Thanks,
{owner_email or 'Form Automation System'}"""

        try:
            with smtplib.SMTP('smtp.gmail.com', 587) as server:
                server.starttls()
                server.login(sender_email, sender_password)
                for email in [e.strip() for e in colleagues.split(',') if e.strip()]:
                    msg = MIMEMultipart()
                    msg['From'] = sender_email
                    msg['To'] = email
                    msg['Subject'] = subject
                    msg.attach(MIMEText(body, 'plain'))
                    server.sendmail(sender_email, email, msg.as_string())
                    st.write(f"✅ Sent to {email}")
            st.success("All emails sent successfully!")
        except Exception as e:
            st.error(f"❌ Error sending emails: {e}")

    if st.button("📊 View All Responses"):
        file_path = "data/responses.csv"
        if os.path.exists(file_path):
            responses_df = pd.read_csv(file_path)
            st.dataframe(responses_df)
            st.download_button("⬇️ Download CSV", responses_df.to_csv(index=False), "responses.csv")
        else:
            st.warning("⚠️ No responses yet.")

